version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mercado-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mercado_db
      MYSQL_USER: mercado
      MYSQL_PASSWORD: mercado
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
